jobs:
  build:
    if: github.ref != 'refs/heads/playstore'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      run: ./gradlew test
    - continue-on-error: true
      run: ./gradlew assembleDebug -PdoNotStrip
name: Debug build
on:
  repository_dispatch:
    types: trigger-ga___debug-build.yml
