jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - continue-on-error: true
      name: Run native tests
      run: make run_tests
      working-directory: ./app/src/main/jni/tests
name: Test native code
on:
  repository_dispatch:
    types: trigger-ga___native-tests.yml
